- name: Install dependencies
  apt:
    name: "{{ needed_packages }}"
    state: present

- name: Git checkout 
  git:
    repo: 'https://opendev.org/openstack/openstack-ansible'
    dest: /opt/openstack-ansible
    version: stable/victoria

- name: Copy ssh private key
  ansible.builtin.copy:
    src: provisioner_key
    dest: /root/.ssh/id_rsa
    mode: '600'

- name: Copy ssh public key
  ansible.builtin.copy:
    src: provisioner_key.pub
    dest: /root/.ssh/id_rsa.pub
    mode: '644'

- name: Bootstrap ansible on provisioner 
  ansible.builtin.shell: 
    cmd: scripts/bootstrap-ansible.sh > /var/log/bootstrap-ansible.log
    chdir: /opt/openstack-ansible

- name: Copy openstack deployment files from installer
  ansible.builtin.copy:
    src: /opt/openstack-ansible/etc/openstack_deploy/
    dest: /etc/openstack_deploy/
    mode: '644'
    remote_src: yes

- name: Copy openstack deployment configuration
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/openstack_deploy/
    mode: '644'
  with_fileglob:
    - "openstack_deploy/*"

# - name: Copy hosts file
#   ansible.builtin.copy:
#     src: "hosts"
#     dest: /etc/openstack_deploy/inventory.ini
#     mode: '644'

# - name: Update hosts
#   ansible.builtin.shell: 
#     cmd: "sed -i 's/ansible_ssh_private_key_file=provisioner_key//g' /etc/openstack_deploy/inventory.ini"

- name: Generate user_secrets tokens
  ansible.builtin.shell: 
    cmd: scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
    chdir: /opt/openstack-ansible